version: '3'

services:
  litterarum-dashboard:
    container_name: litterarum-dashboard  
    image: ghcr.io/mandragora-hub/litterarum-dashboard:main
    build:
      context: .
    ports:
    - 3000:3000    