
services:
  litterarum-dashboard:
    container_name: litterarum-dashboard  
    image: ghcr.io/mandragora-hub/litterarum-dashboard:main
    build:
      context: .
    ports:
    - 3000:3000    
    environment:
      - BACKEND_REST_API_URL=${BACKEND_REST_API_URL}
      - BACKEND_REST_API_TOKEN=${BACKEND_REST_API_TOKEN}
      - METADATA_EXTRACTOR_URL=${METADATA_EXTRACTOR_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - HOST=${HOST}
